- ispdb/hotmail.com
It's no error that pop3 and imap are configured to the same server, see also https://support.office.com/en-us/article/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040
> New/recommended settings from Microsoft

- ispdb/hotmail.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1571772
Older clients will ignore this change, but newer clients will offer Exchange as an alternative.
> Allow Exchange account for Office 365

- ispdb/hotmail.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1583777
Older clients will ignore this change, but newer clients will skip the creation of the SMTP server.
> Disable SMTP server when creating OWL account

- ispdb/hotmail.com
- ispdb/office365.com
- ispdb/outlook.com
We want IMAP to be the default for Hotmail accounts (including hotmail.de,
live.com, outlook.com, outlook.de etc.).
However, due to the MX setup, Office365 accounts also draw the same config
as for outlook.com. Bug 1185366 fixes this, by allowing 2 separate configs
for Office365 and Hotmail.
But that won't help clients already deployed. In the interim, as a hotfix,
split the config into 3 configs:
* Config for Office365. This requires bug 1185366 fixed.
* Config for @hotmail.com, @hotmail.de, @live.com, @live.de, @outlook.de,
and all other known domains, but not outlook.com. This will be active
for all clients immediately and default to IMAP instead of Exchange.
* Config for outlook.com only. Until bug 1185366 is fixed, this will be
used for @outlook.com (exactly this) and all Office365 …
> Split outlook.com to demote Exchange for Hotmail

- ispdb/office365.com
- ispdb/outlook.com
Move exhange type accounts last on the incoming server list, so exchange doesn't inadvertently get set as default.
Fixes the "default" part of https://bugzilla.mozilla.org/show_bug.cgi?id=1592258
> Move exhange type accounts last on the incoming server list

- ispdb/aol.com
@benbucksch or @jorgk3  , Can you review this PR? This is breaking a few AOL domains on Thunderbird.
> Update aol.com to include netscape.com, compuserve.com and cs.com as they are currently defaulting to yahoo provider

- ispdb/aol.com
- ispdb/googlemail.com
- ispdb/mail.ru
- ispdb/office365.com
- ispdb/yahoo.com
- ispdb/yandex.ru
OAuth2 doesn't work unless the client knows certain OAuth2 parameters. Add them to the configs of those ISPs that use OAuth2.
Does not include the client key.
> Add OAuth2 parameters to the ISPs that use OAuth2 #18

- ispdb/t-online.de
Related to: https://github.com/thundernest/autoconfig/issues/25
I added the SMTP SSL/TLS config for t-online.de after successfully testing it.
The official reference by T-Online.de / Telekom can be found here (in German):
[https://www.telekom.de/hilfe/festnetz-internet-tv/e-mail/e-mail-server-e-mail-protokolle-und-e-mail-einrichtung/posteingangsserver-und-postausgangsserver](https://www.telekom.de/hilfe/festnetz-internet-tv/e-mail/e-mail-server-e-mail-protokolle-und-e-mail-einrichtung/posteingangsserver-und-postausgangsserver)
> add SMTP SSL/TLS for t-online.de

- ispdb/biglobe.ne.jp
SSL connection has been mandatory for the provider.
> supporting POP/SMTP over SSL for Biglobe.ne.jp

- ispdb/schwaz.net
This adds proper configuration for the local provider schwaz.net in lovely Tyrol, Austria. The automatically derived values so far yield a nonworking configuration, I haven't been able to figure out whether this is a misconfiguration of the provider at the DNS level or just insufficient guesses. The static client config corresponds to the officially documented (and tested) [settings](https://stadtwerkeschwaz.at/schwaz-net/anleitungen#Einstellungen), only preferring SSL over STARTTLS for SMTP against the provider's stated order of preference.
> Add schwaz.net autoconfig

- ispdb/umich.edu
Update to previous ISPDB change request from 20220627. Includes standard password login as a back-up, if OAuth2 does not work.
> UPDATE: umich.edu 20220628

- ispdb/cloudnine-net.jp
The "empty" file was added to work around problems when trying to get rid of a previously valid config on the production server. Nowadays the deployment script replaces whole directories and thus correctly gets rid of previously used configs.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1223709
In a fun twist, this lead to the deployment script [update.sh](https://github.com/thundernest/thundernest-ansible/blob/ba8d35e68415b3d4a05943b9d2ff649d9f92362f/files/update.sh#L19) including a work-around to avoid an error when converting configs to version 1.0.
The pull request to clean up the deployment script after this has been merged: https://github.com/thundernest/thundernest-ansible/pull/31
> Remove unused file

- tools/convert.py
Because this functionality was broken and nobody seemed to be bothered by it, one could make an argument for removing the code. However, I find these features useful for debugging. So I'm in favor of keeping them around.
> Fix features in convert.py that are not used in the deployment workflow

- .github/workflows/validate-config.yml
This adds a GitHub workflow to validate file extensions on pull requests. The check can be seen in action here:
- https://github.com/cketti/autoconfig/pull/2
- https://github.com/cketti/autoconfig/pull/3
The error message is added as an annotation to the file with the wrong extension. See https://github.com/cketti/autoconfig/pull/2/files
>  Add GitHub workflow to validate file extensions

- ispdb/free.fr.xml
Previously:
* In the past, the large French ISP free.fr (about 30% market share) didn't have an SMTP server that works everywhere, both in their network and outside. So, users needed 2 slightly different configurations for when they are at home and when they are elsewhere. No config would work in both places.
* Additionally, free didn't allow SSL for SMTP, considering it unnecessary.
Changes:
* Luckily, they now allow an SSL config for SMTP. This PR updates our config file to this improvement.
* The documentation URL has changed
* I've also added the webmail config, just for those clients who need it.
> free.fr: Use SSL for SMTP

- ispdb/charter.com.xml
The file started with the 3 bytes `EF BB BF`, the UTF-8 representation of the [BOM](https://en.wikipedia.org/wiki/Byte_order_mark). This is unnecessary. And the XML parser we're using on Android throws an exception when trying to read the file.
> Remove UTF-8 BOM

- ispdb/mnet.ne.jp.xml
I wasn't able to find a web page under the domain mnet.ne.jp listing these server settings. However, various third-party email clients use these. And I manually verified that IMAP/POP/SMTP servers are reachable using these settings.
> Update settings for mnet.ne.jp

- ispdb/jet.ne.jp.xml
In PR #57 I accidentally set the `socketType` value to `STARTSSL` instead of `STARTTLS`.
> jet.ne.jp: Fix 'socketType' value

- ispdb/me.com.xml
- Replaced deprecated `authentication` value of `plain` with `password-cleartext` (outgoing server).
- Removed commented-out, non-working `outgoingServer` entry.
- For the outgoing server, changed `username` value from `%EMAILLOCALPART%` to `%EMAILADDRESS%` because that's what the provider's documentation says. I've verified with an `@icloud.com` account that this works.
- Added documentation tag.
> Update settings for iCloud Mail

- ispdb/alice.it.xml
This is part of my mission to eradicate entries without transport encryption (`<socketType>plain</socketType>`).
> Update settings for alice.it

- ispdb/yahoo.com.xml
Yahoo has an "export" IMAP server endpoint that allows to download more than 10k messages, but is read-only. https://help.yahoo.com/kb/download-email-yahoo-mail-third-party-sln28681.html
This is provided as a "Takeout" feature (when you go to https://mail.yahoo.com/getmydata, it links to the help document above), so it will probably only get used by people changing the server address manually.
Adding it here allows this endpoint to use the OAuth login method.
> Add Yahoo export IMAP server

- ispdb/charter.com.xml
- ispdb/charter.net.xml
- Removes entries with `<socketType>plain</socketType>`.
- Adds POP3 settings.
- Adds the domains `spectrum.net` and `bresnan.net` that use the same mail server settings.
https://www.spectrum.net/support/internet/mobile-email-setup
> Update settings for Charter

- ispdb/bigpond.com.xml
- ispdb/mail.telenor.dk.xml
- ispdb/rambler.ru.xml
- ispdb/ziggo.nl.xml
- ispdb/zoho.com.xml
According to the format specification `documentation` elements go inside the `emailProvider` element.
> Move `documentation` elements to their specified place

- ispdb/web.de.xml
as requested in #83, I opened independent PRs for these commits.
The only thing I had to adjust was the position of the enable element (See https://github.com/thunderbird/autoconfig/pull/84#issuecomment-1874793801 if you want to know why)
> web.de: add SMTP SSL, webMail and enable, update documentation

- docs/client-support.md
Having such a list is useful when trying to find out whether a planned change like #96 impacts anyone.
> Add list of clients supporting Autoconfig/ISPDB

- ispdb/gmx.net.xml
We have a separate config for gmx.com already.
This partially reverts a change from #91.
> Remove gmx.com from gmx.net config

- ispdb/cc9.ne.jp.xml
Mail servers can be reached using these settings. Due to lack of an account I wasn't able to test authentication. But what we have now is more likely to work than what was there before.
> Update settings for cc9.ne.jp

- docs/client-support.md
[Himalaya](https://github.com/soywod/himalaya) is a CLI that relies on Autoconfig/ISPDB to discover accounts. It also extends it to SRV DNS records in case of failure.
> Add Himalaya

- ispdb/earthlink.net.xml
Updating this because a K-9 Mail user [reported](https://forum.k9mail.app/t/earthlink-imap-not-working/8571) an Earthlink related issue that made me realize automatic setup didn't work for them. That's because K-9 Mail ignores entries not using any transport encryption.
I changed the authentication method for the outgoing server to `password-cleartext` because the server only announces support for `PLAIN` and `LOGIN`.
```text
> EHLO autoconfig.test
< 250-hello TLS
< 250-AUTH LOGIN PLAIN
< 250-8BITMIME
< 250-PIPELINING
< 250-HELP
< 250-CHUNKING
< 250-BINARYMIME
< 250 SIZE 52428800
``` 
Earthlink documentation: https://help.earthlink.net/portal/en/kb/articles/email-server-settings
> Update settings for earthlink.net

- ispdb/strato.de.xml
They removed support for CRAM-MD5 and don't support any other encrypted authentication methods.
See https://www.strato.de/faq/mail/externes-e-mail-programm-mit-strato-e-mail-adresse-nutzen/
(I am a customer and was notified of this via email)
> Update settings for Strato

- ispdb/email.it.xml
It looks like the provider recently changed its business model and server settings. See <https://www.email.it/welcome> and <https://www.email.it/faq>.
I verified the server settings using:
```shell
openssl s_client -connect in.email.it:993 -crlf -verify_hostname in.email.it -ign_eof <<EOF
1 ID ("name" "autoconfig.test")
EOF
```
```shell
openssl s_client -connect pop.email.it:995 -crlf -verify_hostname pop.email.it -ign_eof <<EOF
CAPA
EOF
```
```shell
openssl s_client -connect out.email.it:465 -crlf -verify_hostname out.email.it -ign_eof <<EOF
EHLO autoconfig.test
EOF
```
Closes #116
> Update settings for email.it

- ispdb/oxcloud-eu.xml
- ispdb/oxcloud-us.xml
Due to our global business selling EMail-Cloud-Services to several ISPs we need to have (for now) two different configurations  (US and EU).
We also rely on Thunderbird's intermediate MX lookup since we do not have any control over enduser's mail domains. Please let me know if there are any concerns. I'm open to discuss them.
> Add entries for OX Cloud EU and US

- ispdb/hotmail.com.xml
As per https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040, Microsoft recommends using smtp-mail.outlook.com as an Outlook SMTP server.
> Update SMTP settings for Microsoft Outlook accounts

- ispdb/mit.edu.xml
Hello all, I believe we (MIT) meet the criteria for inclusion in this database, though it wasn't clear to me if you preferred a submission on bugzilla or a PR here (it looks like both are happening, but please let me know if you'd like me to submit this differently.)
We have a slightly nonstandard config (for approximately good reasons), and due to some infrastructure complexities on our end, would prefer to have this config hosted by you if that's agreeable.
Please let me know if there are any questions about any of this.
Thanks!
> Add config for MIT.EDU

- ispdb/hotmail.com.xml
Microsoft no longer support basic authentication. See https://support.microsoft.com/en-us/office/outlook-and-other-apps-are-unable-to-connect-to-outlook-com-when-using-basic-authentication-f4202ebf-89c6-4a8a-bec3-3d60cf7deaef for more details.
> Remove plain text authentication for Microsoft accounts

- ispdb/rediffmail.com.xml
Rediffmail is a famous free email provider in India. Add SMTP and POP3 settings for the same. It does not support IMAP in its free plan.
> Add settings for free rediffmail accounts

- ispdb/verizon.net.xml
Using the AOL names directly (they are the same servers) so OAuth2 will work.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1978413
See https://www.verizon.com/support/residential/announcements/email-policy-announcement
> Add verizon IMAP configuration and reflect that's it's now AOL.
